[package]
name = "kasugai_canvas"
version = "2.0.5"
edition = "2021"
description = "KASUGAI Canvas CesiumJS and Three.js viewer"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "time"] }
tower-http = { version = "0.6", features = ["fs"] }

[build-dependencies]
winres = "0.1.12"
